version: 0.2

phases:
  build:
    commands:
    - echo "This is build phase... Zipping my lambda function"
    - zip -r node-lambda-function.zip node-index.js
  post_build:
    commands:
    - echo "Deploying to the Lambda"
    - aws lambda update-function-code --function-name my-lambda --zip-file fileb://node-lambda-function.zip 
artifacts:
  type: zip
  paths:
    - '*'
    
    
   
