version: 0.2

phases:
  build:
    commands:
    - echo "This is build phase... Zipping my lambda function"
    - zip -r mylembda-fuction.zip lambda_function.py
  post_build:
    commands:
    - echo "Deploying to the Lambda"
    - aws lambda update-function-code --function-name mylembda-fuction --zip-file fileb://mylembda-fuction.zip
artifacts:
  type: zip
  paths:
    - '*'
    
    
   
